* Soft Dev
** 4/4/16 - Aim: Feel the Bind, Part Deux
A python function has an inner function, does this constitute a closure?
Nah
*** Closures:
**** A function is declared inside another function
**** Inner Function access a variable from the outer funtion (outside of the local scope of the inner function
**** The external function binds a value to the variable and finishes (or closes) befire the inner function can be completed
#+BEGIN_SRC python
  def repeat(s):
      def times(x):
          return s* times
      return times
#+END_SRC
*** r1 = repeat("hello")
*** This creates a closure because repeat runs, binds s to "hello", and then exits, returning a functions (times) with s bound to "hello"

